### ISSUE TITLE
`make presto-cli` does not work

### ISSUE THREAD

**Issue by zhenik** [fredrikhgrelland/terraform-nomad-presto#54]
## Current behaviour
`show catalogs;` throw the error

## Expected behaviour
```
presto:default> show catalogs;
 Catalog 
---------
 hive    
 jmx     
 memory  
 system  
 tpcds   
 tpch    
(6 rows)

Query 20201026_132630_00069_hhwdp, FINISHED, 1 node
http://localhost:8080/ui/query.html?20201026_132630_00069_hhwdp
Splits: 19 total, 19 done (100.00%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 5% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 0B
0.47 [0 rows, 0B] [0 rows/s, 0B/s]
```
## How to reproduce?
0. `make up`
1. `make presto-cli`
2. `show catalogs;`

Log

```
 ~/src/github.com/zhenik/terraform-nomad-presto │ master *1 !1  make presto-cli                                                                                                                                     ✔ │ 11s │ 14:27:29 
Makefile:77: warning: overriding recipe for target 'status'
Makefile:60: warning: ignoring old recipe for target 'status'
CID=$(docker run --rm -d --network host consul:1.8 connect proxy -token master -service presto-local -upstream presto:8080)
docker run --rm -it --network host prestosql/presto:341 presto --server localhost:8080 --http-proxy localhost:8080 --catalog hive --schema default --user presto --debug
docker rm -f $CID
presto:default> show catalogs;
Error running command: java.net.SocketException: Connection reset
java.io.UncheckedIOException: java.net.SocketException: Connection reset
        at io.prestosql.client.JsonResponse.execute(JsonResponse.java:154)
        at io.prestosql.client.StatementClientV1.<init>(StatementClientV1.java:134)
        at io.prestosql.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
        at io.prestosql.cli.QueryRunner.startInternalQuery(QueryRunner.java:146)
        at io.prestosql.cli.QueryRunner.startQuery(QueryRunner.java:132)
        at io.prestosql.cli.Console.process(Console.java:347)
        at io.prestosql.cli.Console.runConsole(Console.java:273)
        at io.prestosql.cli.Console.run(Console.java:172)
        at io.prestosql.cli.Console.call(Console.java:101)
        at io.prestosql.cli.Console.call(Console.java:74)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at io.prestosql.cli.Presto.main(Presto.java:32)
Caused by: java.net.SocketException: Connection reset
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at io.prestosql.client.OkHttpUtil.lambda$interceptRequest$3(OkHttpUtil.java:106)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at io.prestosql.client.JsonResponse.execute(JsonResponse.java:131)
        ... 17 more
presto:default> 
```
## Suggestion(s)/solution(s) [Optional]
Fix proxy and cli commands
## Checklist (after created issue)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by zhenik** [comment]
The problem was that users run some make commands with `sudo`.
